#!/bin/bash
# Gravitino Quickstart Setup
# Run this once before docker compose up -d

set -e

echo ""
echo "╔════════════════════════════════════════════════╗"
echo "║     Gravitino Quickstart Setup                 ║"
echo "╚════════════════════════════════════════════════╝"
echo ""

# Check if .env already exists
if [ -f .env ]; then
    echo "An existing .env file was found."
    read -p "Reconfigure? [y/N]: " reconfigure
    if [[ ! "$reconfigure" =~ ^[Yy]$ ]]; then
        echo "Using existing .env. Run 'docker compose up -d' to start."
        exit 0
    fi
fi

echo ""
echo "The quickstart includes these catalogs by default:"
echo "  • postgres_demo  — ADP financial services data (PostgreSQL)"
echo "  • hive_nyc       — NYC Yellow Taxi data (Hive/Parquet)"
echo "  • fileset_nyc    — NYC Yellow Taxi files (governance)"
echo ""
echo "Optional: Iceberg catalog (iceberg_nyc)"
echo "  Requires an S3 bucket or S3-compatible storage (MinIO, Dell ECS, etc.)"
echo "  Press Enter to skip all S3 prompts and run without Iceberg."
echo ""

read -p "Enable Iceberg catalog? [y/N]: " enable_iceberg

if [[ "$enable_iceberg" =~ ^[Yy]$ ]]; then
    echo ""
    echo "Enter your S3 credentials (Ctrl+C to abort):"
    echo ""
    read -p "AWS_ACCESS_KEY_ID: " aws_key
    read -s -p "AWS_SECRET_ACCESS_KEY: " aws_secret
    echo ""
    read -p "S3_BUCKET (e.g. my-iceberg-bucket): " s3_bucket
    read -p "AWS_REGION [us-east-1]: " aws_region
    aws_region=${aws_region:-us-east-1}
    read -p "S3_ENDPOINT (leave blank for AWS, or e.g. http://minio:9000): " s3_endpoint

    cat > .env << ENVEOF
# Gravitino Quickstart Configuration
# Generated by setup.sh

ICEBERG_ENABLED=true
AWS_ACCESS_KEY_ID=${aws_key}
AWS_SECRET_ACCESS_KEY=${aws_secret}
AWS_REGION=${aws_region}
S3_BUCKET=${s3_bucket}
S3_ENDPOINT=${s3_endpoint}
S3_ICEBERG_WAREHOUSE=s3://${s3_bucket}/iceberg
ENVEOF

    echo ""
    echo "✓ Iceberg catalog enabled with S3 backend"
else
    cat > .env << ENVEOF
# Gravitino Quickstart Configuration
# Generated by setup.sh

ICEBERG_ENABLED=false
ENVEOF
    echo ""
    echo "✓ Iceberg catalog disabled (PostgreSQL + Hive + Fileset only)"
fi

echo ""
echo "Setup complete. Run the following to start the stack:"
echo ""
echo "  docker compose up -d"
echo ""

