connector.name=singlestore
connection-url=jdbc:singlestore://svc-3482219c-a389-4079-b18b-d50662524e8a-shared-dml.aws-virginia-6.svc.singlestore.com:3333/db_mark_e82d3?sslMode=REQUIRED
connection-user=${ENV:SINGLESTORE_USER}
connection-password=${ENV:SINGLESTORE_PASSWORD}
