# Gravitino server config
gravitino.server.webserver.host = 0.0.0.0
gravitino.server.webserver.httpPort = 8090

# Use PostgreSQL as entity store
gravitino.entity.store = relational
gravitino.entity.store.relational.jdbcUrl = jdbc:postgresql://postgres:5432/gravitino_meta
gravitino.entity.store.relational.jdbcUser = gravitino
gravitino.entity.store.relational.jdbcPassword = gravitino
gravitino.entity.store.relational.jdbcDriver = org.postgresql.Driver
